name: CI

on:
  push:
    branches:
      - development
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.1"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Build
        run: |
          npm i
          npm run build

      - name: eslint & prettier
        run: |
          mapfile -t tsfiles < <(git diff --name-only --diff-filter=AM HEAD^ HEAD | grep '.*\.ts$')
          if [ ${#tsfiles[@]} -ne 0 ]; then
            npx eslint "${tsfiles[@]}"
            npx prettier --check "${tsfiles[@]}"
          fi
